window:
  padding:
    x: 5
    y: 5
font:
  #normal:
    #family: MesloLGLDZ Nerd Font
    #style: Regular
  size: 9
colors:
  name: Neon
  author: ""
  primary:
    background: "#262626"
    foreground: "#f8f8f8"
  cursor:
    text: "#171717"
    cursor: "#f8f8f8"
  normal:
    black: "#171717"
    red: "#d81765"
    green: "#97d01a"
    yellow: "#ffa800"
    blue: "#16b1fb"
    magenta: "#ff2491"
    cyan: "#0fdcb6"
    white: "#ebebeb"
  bright:
    black: "#38252c"
    red: "#ff0000"
    green: "#76b639"
    yellow: "#e1a126"
    blue: "#289cd5"
    magenta: "#ff2491"
    cyan: "#0a9b81"
    white: "#f8f8f8"
scrolling:
  history: 100000
  multiplier: 3
  faux_multiplier: 3
  auto_scroll: false
